<script setup lang="ts">
import { usePage } from '@inertiajs/vue3';
import { UserRoundIcon, XIcon } from 'lucide-vue-next';
import { computed, onBeforeUnmount, ref, watch } from 'vue';
import { Button } from '@/components/ui/button';

/**
 * One photo on a record: the panel shown beside a form's fields.
 *
 * Nothing is uploaded here — the file travels with the form it sits in, so an
 * abandoned form leaves nothing behind. `currentUrl` is what the record
 * already has; clearing that sets `removed`, which the form sends as its own
 * intent so the backend can tell "no new photo" from "delete the photo".
 */
const file = defineModel<File | null>({ default: null });
const removed = defineModel<boolean>('removed', { default: false });

const props = defineProps<{
    /** Already-stored photo, generated by the backend. */
    currentUrl?: string | null;
    /** Falls back to a person outline. */
    alt?: string;
    error?: string;
}>();

const page = usePage();
const input = ref<HTMLInputElement | null>(null);
const rejected = ref<string | null>(null);
const preview = ref<string | null>(null);

const limits = computed(() => {
    const shared = (page.props.fileLimits ?? {}) as {
        mimes?: string[];
        maxKilobytes?: number;
    };

    return {
        mimes: shared.mimes ?? ['jpg', 'jpeg', 'png', 'webp'],
        maxKilobytes: shared.maxKilobytes ?? 5120,
    };
});

const accept = computed(() =>
    limits.value.mimes.map((extension) => `.${extension}`).join(','),
);

const hint = computed(() => {
    const names = limits.value.mimes
        .filter((extension) => extension !== 'jpeg')
        .map((extension) => extension.toUpperCase());
    const megabytes = limits.value.maxKilobytes / 1024;

    return `${names.join(', ')} · up to ${Number.isInteger(megabytes) ? megabytes : megabytes.toFixed(1)} MB`;
});

/** What to show: the chosen file, else the stored one, unless it was cleared. */
const shown = computed(() => preview.value ?? (removed.value ? null : (props.currentUrl ?? null)));

watch(file, (next) => {
    if (preview.value) {
        URL.revokeObjectURL(preview.value);
        preview.value = null;
    }

    if (next) {
        preview.value = URL.createObjectURL(next);
    }
});

onBeforeUnmount(() => {
    if (preview.value) {
        URL.revokeObjectURL(preview.value);
    }
});

function pick() {
    input.value?.click();
}

function onSelected(event: Event) {
    const element = event.target as HTMLInputElement;
    const chosen = element.files?.[0] ?? null;

    element.value = '';

    if (!chosen) {
        return;
    }

    // Checked here for the same reasons the request checks it, so the refusal
    // is immediate rather than a round trip.
    const extension = chosen.name.split('.').pop()?.toLowerCase() ?? '';

    if (!limits.value.mimes.includes(extension)) {
        rejected.value = 'That file is not an accepted image type.';

        return;
    }

    if (chosen.size > limits.value.maxKilobytes * 1024) {
        rejected.value = `That image is larger than ${limits.value.maxKilobytes / 1024} MB.`;

        return;
    }

    rejected.value = null;
    removed.value = false;
    file.value = chosen;
}

/** Clear both a newly chosen file and an already-stored photo. */
function clear() {
    rejected.value = null;
    file.value = null;
    removed.value = Boolean(props.currentUrl);
}
</script>

<template>
    <div class="space-y-2">
        <div
            class="relative flex aspect-[4/3] w-full items-center justify-center overflow-hidden rounded-lg border border-border bg-muted/40"
        >
            <img
                v-if="shown"
                :src="shown"
                :alt="alt ?? 'Photo'"
                class="size-full object-cover"
            />
            <UserRoundIcon v-else class="size-9 text-muted-foreground/60" />

            <Button
                v-if="shown"
                type="button"
                variant="outline"
                size="icon-dense"
                class="absolute end-2.5 top-2.5 bg-background"
                aria-label="Remove photo"
                @click="clear"
            >
                <XIcon />
            </Button>

            <Button
                type="button"
                variant="outline"
                size="dense"
                class="absolute end-2.5 bottom-2.5 bg-background"
                @click="pick"
            >
                {{ shown ? 'Change' : 'Upload' }}
            </Button>

            <input
                ref="input"
                type="file"
                class="hidden"
                :accept="accept"
                @change="onSelected"
            />
        </div>

        <p v-if="rejected || error" class="text-2xs text-danger">
            {{ rejected ?? error }}
        </p>
        <p v-else class="text-center text-2xs text-muted-foreground">{{ hint }}</p>
    </div>
</template>
