<script setup lang="ts">
import { router, useForm, usePage } from '@inertiajs/vue3';
import { ChevronDownIcon, ChevronUpIcon, CloudUploadIcon, ImageIcon, StarIcon, Trash2Icon } from 'lucide-vue-next';
import { computed, ref } from 'vue';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

export interface ProductImage {
    id: number;
    /** Generated by the backend from the configured disk. */
    url: string | null;
    original_name: string | null;
    size: number | null;
    sort_order: number;
    is_primary: boolean;
}

/**
 * Upload, promote, reorder and remove a product's images.
 *
 * Talks only in ids and files. It never sees a disk name and never builds a
 * URL — the backend sends one with each image, so switching storage provider
 * changes nothing here.
 */
const props = defineProps<{
    productId: number;
    images: ProductImage[];
    /** Hidden entirely when the viewer cannot edit the product. */
    editable?: boolean;
}>();

const page = usePage();
const fileInput = ref<HTMLInputElement | null>(null);
const dragging = ref(false);

/** The limits the request validates against, shared from config/files.php. */
const limits = computed(() => {
    const shared = (page.props.fileLimits ?? {}) as {
        mimes?: string[];
        maxKilobytes?: number;
    };

    return {
        mimes: shared.mimes ?? ['jpg', 'jpeg', 'png', 'webp'],
        maxKilobytes: shared.maxKilobytes ?? 5120,
    };
});

const accept = computed(() =>
    limits.value.mimes.map((extension) => `.${extension}`).join(','),
);

const hint = computed(() => {
    const names = limits.value.mimes
        .filter((extension) => extension !== 'jpeg')
        .map((extension) => extension.toUpperCase());
    const megabytes = limits.value.maxKilobytes / 1024;

    return `${names.join(', ')}, up to ${Number.isInteger(megabytes) ? megabytes : megabytes.toFixed(1)} MB each.`;
});

const uploadForm = useForm<{ images: File[] }>({ images: [] });

const ordered = computed(() =>
    [...props.images].sort((a, b) => a.sort_order - b.sort_order || a.id - b.id),
);

function pick() {
    fileInput.value?.click();
}

function onSelected(event: Event) {
    const input = event.target as HTMLInputElement;

    upload(Array.from(input.files ?? []));
    input.value = '';
}

function onDrop(event: DragEvent) {
    dragging.value = false;
    upload(Array.from(event.dataTransfer?.files ?? []));
}

function upload(files: File[]) {
    const images = files.filter((file) => file.type.startsWith('image/'));

    if (!images.length) {
        return;
    }

    uploadForm.images = images;
    uploadForm.post(`/inventory/products/${props.productId}/images`, {
        preserveScroll: true,
        forceFormData: true,
        onSuccess: () => uploadForm.reset('images'),
    });
}

function makePrimary(image: ProductImage) {
    router.patch(
        `/inventory/products/${props.productId}/images/${image.id}/primary`,
        {},
        { preserveScroll: true },
    );
}

function remove(image: ProductImage) {
    router.delete(`/inventory/products/${props.productId}/images/${image.id}`, {
        preserveScroll: true,
    });
}

/** Move an image one place and persist the whole order. */
function move(image: ProductImage, offset: number) {
    const ids = ordered.value.map((candidate) => candidate.id);
    const from = ids.indexOf(image.id);
    const to = from + offset;

    if (from === -1 || to < 0 || to >= ids.length) {
        return;
    }

    ids.splice(to, 0, ids.splice(from, 1)[0]);

    router.patch(
        `/inventory/products/${props.productId}/images/reorder`,
        { images: ids },
        { preserveScroll: true },
    );
}

function readableSize(bytes: number | null): string {
    if (!bytes) {
        return '—';
    }

    return bytes >= 1024 * 1024
        ? `${(bytes / 1024 / 1024).toFixed(1)} MB`
        : `${Math.round(bytes / 1024)} KB`;
}
</script>

<template>
    <div class="space-y-4">
        <div
            v-if="editable"
            class="flex cursor-pointer flex-col items-stretch rounded-md border border-dashed transition-colors"
            :class="
                dragging
                    ? 'border-primary bg-accent/60'
                    : 'border-input bg-muted/40 hover:bg-muted/60'
            "
            @click="pick"
            @dragover.prevent="dragging = true"
            @dragleave.prevent="dragging = false"
            @drop.prevent="onDrop"
        >
            <div class="grow p-5 text-center">
                <div
                    class="mx-auto mb-3 flex size-8 items-center justify-center rounded-full border border-border bg-background"
                >
                    <CloudUploadIcon class="size-4 text-muted-foreground" />
                </div>

                <h3 class="mb-0.5 text-xs font-semibold text-foreground">
                    Choose a file or drag &amp; drop here.
                </h3>
                <span class="mb-3 block text-2xs text-muted-foreground">
                    {{ hint }}
                </span>

                <Button type="button" size="dense" @click.stop="pick">
                    Browse File
                </Button>
            </div>

            <input
                ref="fileInput"
                type="file"
                class="hidden"
                :accept="accept"
                multiple
                @change="onSelected"
            />
        </div>

        <p v-if="uploadForm.processing" class="text-2xs text-muted-foreground">
            Uploading…
        </p>
        <p
            v-for="(error, field) in uploadForm.errors"
            :key="field"
            class="text-2xs text-danger"
        >
            {{ error }}
        </p>

        <ul v-if="ordered.length" class="divide-y divide-border rounded-md border border-border">
            <li
                v-for="(image, index) in ordered"
                :key="image.id"
                class="flex items-center gap-3 p-3"
            >
                <div
                    class="flex h-12 w-16 shrink-0 items-center justify-center overflow-hidden rounded-md border border-border bg-muted"
                >
                    <img
                        v-if="image.url"
                        :src="image.url"
                        :alt="image.original_name ?? ''"
                        class="size-full object-contain"
                    />
                    <ImageIcon v-else class="size-4 text-muted-foreground" />
                </div>

                <div class="min-w-0 flex-1">
                    <p class="truncate text-2sm font-medium">
                        {{ image.original_name ?? `Image ${index + 1}` }}
                    </p>
                    <p class="text-2xs text-muted-foreground">
                        {{ readableSize(image.size) }}
                    </p>
                </div>

                <Badge v-if="image.is_primary" variant="info" size="sm">Primary</Badge>

                <div v-if="editable" class="flex shrink-0 items-center gap-1">
                    <Button
                        variant="ghost"
                        size="icon-dense"
                        aria-label="Move up"
                        :disabled="index === 0"
                        @click="move(image, -1)"
                    >
                        <ChevronUpIcon />
                    </Button>
                    <Button
                        variant="ghost"
                        size="icon-dense"
                        aria-label="Move down"
                        :disabled="index === ordered.length - 1"
                        @click="move(image, 1)"
                    >
                        <ChevronDownIcon />
                    </Button>
                    <Button
                        v-if="!image.is_primary"
                        variant="ghost"
                        size="icon-dense"
                        aria-label="Make primary"
                        @click="makePrimary(image)"
                    >
                        <StarIcon />
                    </Button>
                    <Button
                        variant="ghost"
                        size="icon-dense"
                        aria-label="Remove image"
                        @click="remove(image)"
                    >
                        <Trash2Icon />
                    </Button>
                </div>
            </li>
        </ul>

        <p v-else class="text-2xs text-muted-foreground">No images yet.</p>
    </div>
</template>
